### ISSUE TITLE
Selected options on preferences difficult to see

### ISSUE THREAD

**Issue by javaguirre** [a5hk/paper#1]
Hi @a5hk !

I found this issue, the selected preference is not easy to see.

![Screenshot 2023-01-11 at 11 27 24](https://user-images.githubusercontent.com/488556/211783011-ce44ca08-093a-46e9-aa45-432a11ee0aab.png)

Thank you for this great theme!

**Comment by a5hk** [comment]
Hi @javaguirre 

Thank you for reporting this issue, I'll look into that.

**Comment by a5hk** [comment]
@javaguirre, A fixed version is now available on Marketplaces.

**Comment by javaguirre** [comment]
Thank you! Can you link it here? I can't see it

**Comment by a5hk** [comment]
> Thank you! Can you link it here? I can't see it

Sure, 

[Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=a5hk.paper)
[Open VSX Registry](https://open-vsx.org/extension/a5hk/paper)

You should see version 1.1.1

**Comment by javaguirre** [comment]
Thank you!! 💯

**Comment by javaguirre** [comment]
I really like your taste in themes, gonna try the others you have for VS Code 🏆

**Comment by javaguirre** [comment]
@a5hk What theme are you using on that screenshot?

<img width="725" alt="Screenshot 2023-01-12 at 09 59 26" src="https://user-images.githubusercontent.com/488556/212022962-51d476c7-dd3d-450e-b1f5-f1d8604cbaa8.png">

**Comment by a5hk** [comment]
> I really like your taste in themes, gonna try the others you have for VS Code 🏆

Thank you for your interest and kind words.

> @a5hk What theme are you using on that screenshot?

It is [Night Coder](https://marketplace.visualstudio.com/items?itemName=a5hk.night-coder), the main variant. I might have modified it a little since that screenshot.
